unity:
  replicaCount: 0

  image:
    repository: niwrad-unity
    pullPolicy: Never

nakama:
  replicaCount: 1

  image:
    repository: nakama
    pullPolicy: Never

  service:
    type: NodePort
    port: 80 # TODO: ports for nakama

  default:
    username: azerty@azerty.com
    password: azertyazerty


  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  
js:
  replicaCount: 0

  image:
    repository: niwrad-js
    pullPolicy: Never
